//------------------------------------------------------------------------------
// <auto-generated>
// Suppress stylecop rules as this file is deprecated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Dalamud.Game.Gui.ContextMenus
{
    /// <summary>
    /// An indicator displayed on a context menu item.
    /// </summary>
    [Obsolete("This is deprecated and no longer works. Use new context menu events instead.", false)]
    public enum ContextMenuItemIndicator
    {
        /// <summary>
        /// The item has no indicator.
        /// </summary>
        None,

        /// <summary>
        /// The item has a previous indicator.
        /// </summary>
        Previous,

        /// <summary>
        /// The item has a next indicator.
        /// </summary>
        Next,
    }
}
