//------------------------------------------------------------------------------
// <auto-generated>
// Suppress stylecop rules as this file is deprecated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Dalamud.Game.Gui.ContextMenus
{
    /// <summary>
    /// Represents the method the <see cref="ContextMenu.ContextMenuOpened"/> event.
    /// </summary>
    /// <param name="args">The data associated with the <see cref="ContextMenu.ContextMenuOpened"/> event.</param>
    [Obsolete("This is deprecated and no longer works. Use new context menu events instead.", false)]
    public delegate void ContextMenuOpenedDelegate(ContextMenuOpenedArgs args);
}
