//------------------------------------------------------------------------------
// <auto-generated>
// Suppress stylecop rules as this file is deprecated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Dalamud.Game.Gui.ContextMenus
{
    /// <summary>
    /// Represents the method that handles when a <see cref="CustomContextMenuItem"/> is selected.
    /// </summary>
    /// <param name="args">The data associated with the selected <see cref="CustomContextMenuItem"/>.</param>
    [Obsolete("This is deprecated and no longer works. Use new context menu events instead.", false)]
    public delegate void CustomContextMenuItemSelectedDelegate(CustomContextMenuItemSelectedArgs args);
}
