//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Dalamud.Boot.rc
//
#define IDI_ICON1                       101
#define IDS_APPNAME                     102
#define IDS_MSVCRT_ACTION_OPENDOWNLOAD  103
#define IDS_MSVCRT_ACTION_IGNORE        104
#define IDS_MSVCRT_DIALOG_MAININSTRUCTION 105
#define IDS_MSVCRT_DIALOG_CONTENT       106
#define IDS_MSVCRT_DOWNLOADURL          107
#define IDS_INITIALIZEFAIL_ACTION_ABORT 108
#define IDS_INITIALIZEFAIL_ACTION_CONTINUE 109
#define IDS_INITIALIZEFAIL_DIALOG_MAININSTRUCTION 110
#define IDS_INITIALIZEFAIL_DIALOG_CONTENT 111
#define IDS_INITIALIZEFAIL_DIALOG_FOOTER 112

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
