name: Back up code to other forges

on:
  schedule:
    - cron: '0 2 * * *'  # Run every day at 2 AM
  workflow_dispatch:  # Allow manual trigger

jobs:
  push-to-forges:
    runs-on: ubuntu-latest
    if: github.repository == 'goatcorp/Dalamud'
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd #v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.MIRROR_GITLAB_SYNC_KEY }}
            ${{ secrets.MIRROR_CODEBERG_SYNC_KEY }}

      - name: Add remotes & push
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=accept-new"
        run: |
          git remote add gitlab git@gitlab.com:goatcorp/Dalamud.git
          git push gitlab --all --force
          git remote add codeberg git@codeberg.org:goatcorp/Dalamud.git
          git push codeberg --all --force
